# Generated by Django 4.2.30 on 2026-09-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Unclaimed', 'Unclaimed'), ('Claimed', 'Claimed'), ('Completed', 'Completed')], default='Unclaimed', max_length=10)),
                ('claimed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
